export const TRANSLATIONS: { en: string; lt: string }[] = [
  {
    en: 'LT',
    lt: 'EN',
  },
  {
    en: 'You are probably viewing this file from a mobile device. Because of this you will probably not going to be able to check the answers - for that you will need to open this file on a computer.',
    lt: 'Jūs galimai žiūrite šį failą per mobilųjį įrenginį. Dėl šios priežasties Jūs negalėsite pasitikrinti atsakymų – tam prireiks atsidaryti failą per kompiuterį.',
  },
  {
    en: 'This file was generated by Skafis',
    lt: 'Šį failą sugeneravo Skafis',
  },
  {
    en: 'Correct!',
    lt: 'Teisingai!',
  },
  {
    en: 'Incorrect!',
    lt: 'Neteisingai!',
  },
  {
    en: 'Select an answer',
    lt: 'Pasirinkite atsakymą',
  },
  {
    en: 'Check the answer',
    lt: 'Patikrinti atsakymą',
  },
  {
    en: 'Create tests easily!',
    lt: 'Testus kurk lengvai!',
  },
  {
    en: 'This website generates HTML files with questions, where only one answer option is correct. The user of HTML file can then answer the questions and check the answers (each problem separately).',
    lt: 'Šis tinklapis generuoja HTML failus su klausimais, kur tik vienas atsakymo variantas yra teisingas. HTML failo naudotojas tuomet gali atsakyti į klausimus ir pasitikrinti atsakymus (kiekvienos užduoties atskirai).',
  },
  {
    en: "This Skafis version is the most suitable for quick content summarization and students' self-assesment.",
    lt: 'Ši Skafis versija labiausiai tinka greitam turinio kartojimui bei mokinių įsivertinimui.',
  },
  {
    en: 'The process is not saved! When the website is refreshed, all the information disappears!',
    lt: ' Procesas neišsisaugo! Perkrovus puslapį visa informacija pranyks!',
  },
  {
    en: "Hmm, see? There's no ads! Let's keep it that way ;)",
    lt: 'Hmm, matai? Nėra reklamų! Tegu taip ir išlieka ;)',
  },
  {
    en: "I would be really thankful for financial support, for the work I've put it.",
    lt: 'Būčiau labai dėkingas už piniginę paramą, už įdėtą darbą.',
  },
  {
    en: 'Via bank transaction (Payment purpose: Skafis website donation):',
    lt: 'Pavedimu (Pervedimo paskirtis: Skafis tinklapio parama):',
  },
  {
    en: 'Title',
    lt: 'Pavadinimas',
  },
  {
    en: 'Enter the title',
    lt: 'Įveskite pavadinimą',
  },
  {
    en: 'The title is required',
    lt: 'Pavadinimas yra privalomas',
  },
  {
    en: 'Question',
    lt: 'Klausimas',
  },
  {
    en: 'Enter the question text',
    lt: 'Įveskite klausimo formuluotę',
  },
  {
    en: 'Option',
    lt: 'Pasirinkimas',
  },
  {
    en: 'Enter the option text',
    lt: 'Įveskite pasirinkimo formuluotę',
  },
  {
    en: 'Correct answer',
    lt: 'Teisingas atsakymas',
  },
  {
    en: 'Incorrect answer',
    lt: 'Neteisingas atsakymas',
  },
  {
    en: 'Add a question',
    lt: 'Pridėti klausimą',
  },
  {
    en: 'Remove the last question',
    lt: 'Pašalinti paskutinį klausimą',
  },
  {
    en: 'Download questionaire HTML',
    lt: 'Atsisiųsti užduočių HTML',
  },
  {
    en: "Website's source code: ",
    lt: 'Tinklapio kodas: ',
  },
  {
    en: 'Last time updated: ',
    lt: 'Paskutinį kartą atnaujinta: ',
  },
  {
    en: 'My blog and other interesting things here: ',
    lt: "Mano blog'as bei daugiau įdomių dalykų čia: ",
  },
  {
    en: 'Copy',
    lt: 'Kopijuoti',
  },
  {
    en: 'Copied',
    lt: 'Nukopijuota',
  },
  {
    en: "This website uses Google Analytics and tracks only the general analytic information - number of website's visits together with devices' locations to a city approximity. Purpose of data  gathering is to have feedback on how successful the advertising is, and  according to that - adjust activity on improving the website. To know how  Google uses collected data, read about",
    lt: 'Tinklapis naudoja Google Analytics ir seka tik bendrą analitinę informaciją – tinklapio apsilankymų skaičių su prisijungimo vietomis miesto tikslumu. Duomenų rinkimo tikslas – turėti reklaminio sėkmingumo grįžtamąjį ryšį ir pagal tai keisti tinklapio tobulinimo veiklą. Kaip Google naudoja renkamą informaciją, skaitykite apie',
  },
  {
    en: 'Google privacy and terms',
    lt: 'Google privatumą ir sąlygas',
  },
  {
    en: 'All this privacy policy you can always find in the footer of this website.',
    lt: 'Visą šią privatumo politiką Jūs galite visuomet rasti tinklapio poraštėje.',
  },
  {
    en: 'Agree and proceed to the website',
    lt: 'Sutikti ir tęsti lankymąsi tinklapyje',
  },
  {
    en: 'If you disagree, you cannot use this website',
    lt: 'Jeigu nesutinkate, Jūs negalite naudotis šiuo tinklapiu',
  },
  {
    en: 'Privacy policy consent',
    lt: 'Privatumo politikos sutikimas',
  },
  {
    en: 'Expand',
    lt: 'Išskleisti',
  },
  {
    en: "In addition, website uses your browser local storage to store information on whether you agreed with this website's privacy policy. The purpose - user convenience, no consent pop up repetition everytime the website is opened.",
    lt: 'Taip pat, tinklapis naudoja Jūsų naršyklės atmintį, kad patalpintų informaciją apie Jūsų sutikimą su šio tinklapio privatumo politika. Tikslas – naudotojo patogumas, neiššoka sutikimo langas kiekvieną kartą atidarius puslapį.',
  },
];
